### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by MartinMa** [decaporg/one-click-hugo-cms#184]
I did a fresh clone of this repo yesterday and found a bug.

**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Locally (using `yarn start`): Console output `Uncaught SyntaxError: Unexpected token <`.
Netlify live version: 404 for `app.js`.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Clone, run `yarn` and then `yarn start`. Open up dev tools an look a the error in the console.

**- What is the expected behavior?**
No error. No 404 Not Found for `app.js`.

**- Please mention your node.js, NPM, Hugo and operating system version.**
node v10.16.0
npm 6.4.1
Hugo v0.56.3-F637A1EA windows/amd64 BuildDate: 2019-07-31T12:51:49Z
Windows 10

**Comment by martinjagodic** [comment]
Closing in favor of #187
