### ISSUE TITLE
Include working example of hugos image porcessing with netlify

### ISSUE THREAD

**Issue by brasilikum** [decaporg/one-click-hugo-cms#19]
Hugo has powerful image processing capabilities built in, however they are limited to a “Page Bundle” layout, where your images live in the same folder as the content that is referencing them. NetlifyCMS does not (yet?) support this layout.
Instead, all images are stored in one folder under /static.

It is possible to make netlify and Hugo image processing work together by moving the image folder inside of content and making it a “headless” (non-rendered) section. Access can be provided via partials.

I got this to work after a lot of trail and error and I am not exactly sure if I am doing it the best way.

Building an example into this template could probably spare people a lot of experimentation.

**Comment by erquhart** [comment]
Agreed - can you add a description with a little more info?

**Comment by brasilikum** [comment]
Done

**Comment by easherma** [comment]
@brasilikum can you link to your approach? I'm wrestling with the same issue.

**Comment by brasilikum** [comment]
@easherma, sorry, it's not public, but here is the structure I ended up going with:
<img width="200" alt="screen shot 2018-11-07 at 9 51 41 pm" src="https://user-images.githubusercontent.com/3106990/48174817-7d219900-e2d7-11e8-8948-d906c8689272.png">

I am using the following snippet to get a specific image:

```
    {{ $page := . }}
    {{ with $.Site.GetPage "page" "img/index.md" }}
        {{ $imgPath := split $page.Params.images "/"}}
        {{ $img := index $imgPath 2 }}
        {{ with .Resources.GetMatch $img }}
            {{$img400 := .Fill "800x400 Center"}}
            <img src="{{ $img400.RelPermalink }}">
        {{ end }}
    {{ end }}
```

Images are flat under the img directory (because of netlify).

The only non image file is the index.md with the following content:

```
---
title: Images
headless: true
---

```

Hope it helps

**Comment by easherma** [comment]
Interesting! This does help, thanks. :-)

**Comment by amygroshek** [comment]
I know this isn't a place to ask for support, but I want to document here, to prevent others from wasting their time, that I tried the above example and can't seem to get it to work. Adding this to the template:

```
{{ $resourcesArray := .Resources.ByType "image"}}
 <p>{{$resourcesArray}}</p>
```

...shows me that I can in fact get the list of images in the dir. However, I'm not able to GetMatch the single image that I need: 
```
{{ with .Resources.GetMatch $img }}
  {{$img400 := .Fill "800x400 Center"}}
  <img src="{{ $img400.RelPermalink }}">
{{ end }}
```

Results in nothing being printed to the page. And when I try to capture it in a variable and print to the page, I get the error, "Method on nil interface value":

```
{{ $resource := .Resources.GetMatch $img }}
<img src="{{ $resource.RelPermalink }}">
```

Also tried this [example here](https://forestry.io/blog/how-to-use-hugo-s-image-processing-with-forestry/), likewise not working.

**Comment by marcojakob** [comment]
Thanks. Interesting approach.

Using Hugo's image processing will be much more straight forward once NetlifyCMS allow images to be stored relative to content. See https://github.com/netlify/netlify-cms/issues/1472

Then we won't need the workaround with a separate `img` folder in content with a hack using a [headless bundle](https://gohugo.io/content-management/page-bundles/#headless-bundle).

**Comment by curzolapierre** [comment]
Hello, I can see that (https://github.com/netlify/netlify-cms/issues/1472) issue has been fixed now.

What is the current status of the issue here?
What would be the best way to use the image processing now?

I tried to move the images to `site/content/img` but still, it seems that `.Resources.GetMatch` is not able to find them.
