### ISSUE TITLE
/admin load fails

### ISSUE THREAD

**Issue by coldestheart** [decaporg/one-click-hugo-cms#256]
```
Error loading the CMS configuration
Config Errors:

YAMLException: end of the stream or a document separator is expected at line 153, column 19:
    <div style="height: 0; width: 0; position: absolut ... 
                      ^

Check your config.yml file..
```

**Node 12.13 lts** Ubuntu 18

**Comment by erquhart** [comment]
That probably means that you're getting back a 404 HTML page, so the config.yml isn't there. Assuming your cms is at `/admin`, make sure there's a slash _after_ admin, Eg., `/admin/`.

If you see a hash before the slash (`/admin#/`), add a slash before the hash(`/admin/#/`).

**Comment by shanquan** [comment]
find a solution for `/admin` (according to netlify deploy info), you can build first and then just serve dist files.
```
npm run-script build
http-server dist
```

**Comment by martinjagodic** [comment]
I assume this is answered
