### ISSUE TITLE
Feature request: Hamburger menu

### ISSUE THREAD

**Issue by SherG** [decaporg/one-click-hugo-cms#272]
Current menu does not seem to resize properly on smartphones. (See: https://master-template-one-click-hugo-cms.netlify.com/ )

**Comment by erquhart** [comment]
It doesn't resize, it scrolls sideways.

**Comment by raphink** [comment]
@erquhart https://github.com/netlify-templates/one-click-hugo-cms/pull/479 works fine. It'd be great to merge it.

**Comment by Gioele-Bencivenga** [comment]
I also believe the hamburger menu to be a better solution than the horizontal scrolling, users are used to the hamburger but not to the horizontal scroll and this leads to confusion.
