### ISSUE TITLE
[Production mode] Tachyons media queries are not working

### ISSUE THREAD

**Issue by VincentJousse** [decaporg/one-click-hugo-cms#711]
**- Do you want to request a *feature* or report a *bug*?**
a bug

**- What is the current behavior?**
Tachyons media queries are not working in production mode

**- If the current behavior is a bug, please provide the steps to reproduce.**
Display the site on a desktop screen and observe that it is a "small screen" layout.

**- What is the expected behavior?**
Take media queries into account.

**- Please mention your node.js, NPM, Hugo and operating system version.**
Node v17.7.2
Npm 8.5.2,
Hugo-bin 0.89
MacOS Catalina

**Comment by ShohruhAKU** [comment]
I am having a similar issue with the media queries. It works fine when running on local host though. Could you fix it?

**Comment by itomizu** [comment]
in localhost, using `mode: development`. 

This bug happened `sass-loader` in only `mode: 'production'`
So, I rewrite it below and it works.

[webpack.common.js](https://github.com/netlify-templates/one-click-hugo-cms/blob/4e43618d5145f97edf270d4ead9cb577aa4f79b0/webpack.common.js)

```
        test: /\.(sa|sc|c)ss$/,
        exclude: /node_modules/,
        use: [
          "style-loader", 
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              esModule: false
            }
          }, 
          "css-loader",
          "postcss-loader",
           {
            loader: "sass-loader",
            options: {
              sassOptions: {
                outputStyle: "expanded",
              },
            },
          }
        ]
```
