### ISSUE TITLE
Styling appears differently when running locally vs deployed to netlify

### ISSUE THREAD

**Issue by JacobWrenn** [decaporg/one-click-hugo-cms#727]
See the images below. The first is from localhost where everything looks as expected. The second is deployed to Netlify using the one-click option.

![Screenshot 2022-12-07 at 16 57 29](https://user-images.githubusercontent.com/37597713/206242900-e8bb7333-1e45-4048-90a8-e37e2dde4fd5.png)
![Screenshot 2022-12-07 at 16 57 24](https://user-images.githubusercontent.com/37597713/206242920-54fd9395-56fd-4fe6-afc8-0013a4f7af30.png)

**Comment by Gioele-Bencivenga** [comment]
I have the same issue that I'd like to figure out how to solve.

The smaller fonts/tighter UI is not so much of a problem but the horizontal scrollbar that appears in the navbar is quite inconvenient.
And unfortunately the "uglier" version is the deployed one instead of the locally served site.

**Comment by kwuite** [comment]
@JacobWrenn @Gioele-Bencivenga I applied this PR to my fork and it solved my styling issues: https://github.com/netlify-templates/one-click-hugo-cms/pull/742

**Comment by Gioele-Bencivenga** [comment]
@kwuite thanks, found it a short while ago and worked a charm!

**Comment by martinjagodic** [comment]
Solved in #742
