### ISSUE TITLE
Delete master branch and merge #479 into main

### ISSUE THREAD

**Issue by tanyabouman** [decaporg/one-click-hugo-cms#777]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
It looks like the extra master branch caused confusion in https://github.com/decaporg/decap-cms/issues/6832
There's a nice PR that was merged to master that would be really nice to have on main, but it's missing. https://github.com/decaporg/one-click-hugo-cms/pull/479

**- What is the expected behavior?**
Only the main branch exists, and not an additional master branch.

**Comment by martinjagodic** [comment]
@tanyabouman I merged master to main and deleted master.
